# Generated by Django 6.0.2 on 2026-02-11 13:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(help_text="Введите место", max_length=255, verbose_name="Место")),
                (
                    "time",
                    models.DateTimeField(
                        help_text="Введите время для выполнения привычки", verbose_name="Время для выполнения привычки"
                    ),
                ),
                ("action", models.CharField(help_text="Введите действие", max_length=255, verbose_name="Действие")),
                (
                    "is_pleasant_habit",
                    models.BooleanField(
                        default=False, help_text="Укажите флаг приятной привычки", verbose_name="Приятной привычки"
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Укажите периодичность выполнения",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "award",
                    models.CharField(
                        blank=True,
                        help_text="Введите вознаграждение",
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.PositiveSmallIntegerField(
                        help_text="Укажите выполнения выполнения",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(120),
                        ],
                        verbose_name="Время выполнения",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, help_text="Укажите флаг публикации", verbose_name="Публикация"),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите связанную привычку если она имеется",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="atomic_habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["time"],
            },
        ),
    ]
